-- ================================================================
-- ChanhTea Supabase Schema Entry Point
-- ================================================================
--
-- The old single-store schema has been retired.
-- Use the multi-store migrations in this order:
--
--   1. supabase/migrations/001_extensions_enums.sql
--   2. supabase/migrations/002_schema.sql
--   3. supabase/migrations/003_functions_rls.sql
--   4. supabase/migrations/004_seed_demo_data.sql
--
-- Supabase SQL Editor cannot include local files automatically, so copy
-- and run each migration file manually in the order above.
--
-- Images are not stored in Supabase Storage in this architecture.
-- Store only Cloudinary URLs in columns such as:
--   products.image_url
--   stores.image_url
--   profiles.avatar_url
--   order_items.image_url
--
-- Do not expose SUPABASE_SERVICE_ROLE_KEY in frontend JavaScript.
-- Guest order creation should go through a trusted backend or Edge Function.
-- ================================================================
