-- Run this file in Supabase SQL Editor before deploying the app.

CREATE TABLE IF NOT EXISTS products (
  id integer PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  price integer NOT NULL CHECK (price >= 0),
  image text NOT NULL,
  description text NOT NULL,
  sizes text[] NOT NULL DEFAULT '{}',
  toppings text[] NOT NULL DEFAULT '{}',
  popular boolean NOT NULL DEFAULT false,
  badge text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  password text NOT NULL,
  role text NOT NULL DEFAULT 'customer' CHECK (role IN ('admin', 'customer')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  total integer NOT NULL CHECK (total >= 0),
  customer jsonb NOT NULL DEFAULT '{}'::jsonb,
  payment_method text NOT NULL DEFAULT 'cod',
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'preparing', 'delivering', 'done', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products (category);
CREATE INDEX IF NOT EXISTS idx_products_popular ON products (popular);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at DESC);

INSERT INTO products (id, name, category, price, image, description, sizes, toppings, popular, badge)
VALUES
  (1, 'Trà Chanh Cổ Điển', 'tra-chanh', 25000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778052960/TraChanhCoDien_hybj7p.jpg', 'Trà chanh đặc trưng của chúng tôi với hương vị chua ngọt hoàn hảo.', ARRAY['S', 'M', 'L'], ARRAY['Thạch dừa', 'Hạt chia', 'Nata de coco'], true, 'Bán chạy'),
  (2, 'Trà Chanh Muối', 'tra-chanh', 28000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054128/TraChanhMuoi_rmquk9.jpg', 'Kết hợp độc đáo giữa chanh tươi, muối biển và trà xanh vị mặn nhẹ kích thích vị giác.', ARRAY['S', 'M', 'L'], ARRAY['Muối ớt', 'Thạch dừa'], true, 'Đặc biệt'),
  (3, 'Trà Chanh Gừng Mật Ong', 'tra-chanh', 32000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054926/TraMatOng_uuzkiy.jpg', 'Sự kết hợp hoàn hảo của chanh, gừng tươi và mật ong nguyên chất tốt cho sức khỏe.', ARRAY['S', 'M', 'L'], ARRAY['Mật ong thêm', 'Lát gừng'], false, NULL),
  (4, 'Trà Chanh Dây', 'tra-chanh-trai-cay', 30000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054914/TraChanhDay_yn4wyz.jpg', 'Trà xanh kết hợp chanh dây nhiệt đới, chua ngọt tự nhiên đầy thơm mát.', ARRAY['S', 'M', 'L'], ARRAY['Thạch dừa', 'Hạt chia'], true, 'Mới'),
  (5, 'Trà Chanh Việt Quất', 'tra-chanh-trai-cay', 35000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054926/TraChanhVietQuat_dlysxn.jpg', 'Màu tím huyền bí của việt quất hòa quyện cùng vị chua chanh tươi.', ARRAY['S', 'M', 'L'], ARRAY['Việt quất thêm', 'Thạch dừa'], false, 'Mới'),
  (6, 'Trà Chanh Bạc Hà', 'tra-chanh', 30000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054903/TraChanhBacHa_gtnh3r.jpg', 'Với lá bạc hà tươi tạo nên hương vị sảng khoái đặc biệt', ARRAY['S', 'M', 'L'], ARRAY['Đào thêm', 'Nata de coco'], false, NULL),
  (7, 'Trà Chanh Đào', 'tra-chanh-trai-cay', 33000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054914/TraChanhDao_yvokba.jpg', 'Vị ngọt thơm của đào tươi hòa quyện cùng trà chanh mát lạnh.', ARRAY['S', 'M', 'L'], ARRAY['Đào thêm', 'Nata de coco'], false, NULL),
  (8, 'Trà Sữa Chanh', 'tra-sua', 38000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054927/TraSuaChanh_aaullu.jpg', 'Kem sữa béo ngậy trên nền trà chanh chua dịu là sự kết hợp gây nghiện.', ARRAY['M', 'L'], ARRAY['Trân châu', 'Thạch dừa', 'Pudding'], true, 'Hot'),
  (9, 'Trà Chanh Sả Gừng', 'tra-chanh', 30000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054926/TraChanhSaGung_efamgj.jpg', 'Hương sả thơm dịu kết hợp gừng ấm và chanh tươi thanh mát nhưng vẫn đậm vị.', ARRAY['S', 'M', 'L'], ARRAY['Sả tươi', 'Lát gừng', 'Hạt chia'], false, 'Mới'),
  (10, 'Trà Chanh Dưa Lưới', 'tra-chanh-trai-cay', 34000, 'https://res.cloudinary.com/deed7ielg/image/upload/q_auto/f_auto/v1778054915/TraChanhDuaLuoi_rbl8vy.jpg', 'Vị ngọt dịu của dưa lưới kết hợp trà chanh mát lạnh nhẹ nhàng và dễ uống.', ARRAY['S', 'M', 'L'], ARRAY['Dưa lưới', 'Nata de coco'], false, 'Mới')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  image = EXCLUDED.image,
  description = EXCLUDED.description,
  sizes = EXCLUDED.sizes,
  toppings = EXCLUDED.toppings,
  popular = EXCLUDED.popular,
  badge = EXCLUDED.badge;

INSERT INTO users (id, name, email, password, role)
VALUES
  (1, 'Admin', 'admin@chanhtea.vn', 'admin123', 'admin')
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  password = EXCLUDED.password,
  role = EXCLUDED.role;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
