services:
  - type: web
    name: chanh-tea
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
